<?php

/**
 * @file
 * Contains ingredients.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\Node;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\views\Plugin\views\area\View;

/**
 * Implements hook_help().
 */
function ingredients_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ingredients module.
    case 'help.page.ingredients':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module reserved for ingredients.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ingredients_theme() {
  return [
    'ingredients' => [
      'render element' => 'children',
      'variables' => [
       // 'dumpvar' => NULL, s
        'messagevar' => NULL,
      ]
    ],
  ];
}
