<?php

/**
 * @file
 * Primary module hooks for ptest module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
/**
 * Implements hook_theme().
 */
function ptest_theme($existing, $type, $theme, $path) {
  return [
      'page__ptest__example' => [
          'render element' => 'children',
          'variables' => [
              'somevar' => NULL,
          ]
      ]
    ];
}

function ptest_preprocess_page__ptest__example(&$variables) {
    $variables['page']['somevar'] = ['Hola'];
}