<?php

/**
 * @file
 * Contains simpleservice.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function simpleservice_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the simpleservice module.
    case 'help.page.simpleservice':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A simple module trying out custom service that will be used throughout the application.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function simpleservice_theme() {
  return [
    'simpleservice' => [
      'render element' => 'children',
    ],
  ];
}
