<?php

/**
 * @file
 * Contains applications.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function applications_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the applications module.
    case 'help.page.applications':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a module to simply replicate the Applications part on HCMS.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function applications_theme() {
  return [
    'applications' => [
      'render element' => 'children',
    ],
  ];
}
