<?php

/**
 * @file
 * Contains menus.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_help().
 */
function menus_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the menus module.
    case 'help.page.menus':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is all about working with the Menu API.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function menus_theme() {
  return [
    'menus' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_user_login().
 */
function menus_user_login(AccountInterface $account) {
  drupal_set_message("Hello %name. Welcome!", ['%name' => $account->getDisplayName()]);
  return new RedirectResponse(\Drupal::url('<front>', [], ['absolute' => TRUE]));
}
