<?php

/**
 * @file
 * Contains events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\events\Event\UserLoginEvent;
use Symfony\Component\EventDispatcher\EventDispatcher;

/**
 * Implements hook_help().
 */
function events_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the events module.
    case 'help.page.events':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is a custom module for trying out events and events subscribers.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_user_login().
 */
function events_user_login($account) {
  // Create a new instance of our event.
  $event = new UserLoginEvent($account);

  // Get the event_dispatcher server and dispatch the event.

  /**
   * @var EventDispatcher $dispatcher
   */
  $dispatcher = \Drupal::service('event_dispatcher');
  $dispatcher->dispatch(UserLoginEvent::EVENT_NAME, $event);
}
