
products.products_controller_generate:
  path: '/products'
  defaults:
    _controller: '\Drupal\products\Controller\ProductsController::generate'
    _title: 'Products'
  requirements:
    _permission: 'access content'
