<?php

/**
 * @file
 * Contains products.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function products_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the products module.
    case 'help.page.products':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This a custom module for Products.') . '</p>';
      return $output;

    default:
  }
}

// /**
//  * Implements hook_theme().
//  */
// function products_theme() {
//   return [
//     'products' => [
//       'render element' => 'children',
//     ],
//   ];
// }

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 *
 * Checking if test__template is found.
 */
function products_theme_suggestions_views_view_alter(&$suggestions, $variables) {
  $suggestions[] = 'test__template';
  if (in_array('test__template', $suggestions)) {
    print_r('The template is found.');
  } else {
    print_r('Call backup, someone is missing.');
  }
}

/**
 * Implements hook_theme().
 */
function products_theme($existing, $type, $theme, $path) {
  return [
    'products' => [
        'render element' => 'children',
    ]
  ];
}

function products_node_view($node, $view_mode, $langcode) {
  
}

function products_preprocess_node(&$variables){
  $variables['attributes']['class'] = [];
  $variables['attributes']['class'][] = 'node-custom-products';
  $variables['display_submitted'] = FALSE; // Hiding the submitted by part from the node
  // kint($variables);
}

function products_preprocess_field(&$variables) {
  // kint($variables);
}

function products_preprocess_user(&$variables) {

}
