<?php

/**
 * @file
 * Primary module hooks for landing module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

 /**
 * Implements hook_theme().
 */
function landing_theme() {
    return [
      'landing' => [
        'variables' => [
            'content' => NULL,
        ],
      ],
      'landing_bottom' => [
        'variables' => [
          'content_types' => NULL,
        ],
      ],
    ];
  }
